# Generated by Django 5.2.6 on 2025-09-24 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
