# Generated by Django 5.2.6 on 2025-09-25 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0009_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
