# Generated by Django 5.2.6 on 2025-09-25 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0010_profile_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('DEBUG', 'Debug')], max_length=10)),
                ('category', models.CharField(choices=[('DEVICE', 'Device Logs'), ('ACTIVITY', 'Activity Logs'), ('SYSTEM', 'System Logs'), ('USER', 'User Interactions'), ('SECURITY', 'Security Events'), ('NOTIFY', 'Notification Logs')], max_length=20)),
                ('message', models.TextField()),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
