# Generated by Django 5.2.6 on 2025-10-19 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0011_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='log',
            name='category',
            field=models.CharField(choices=[('DEVICE', 'Device Logs'), ('ACTIVITY', 'Activity Logs'), ('SYSTEM', 'System Logs'), ('USER', 'User logs'), ('SECURITY', 'Security Events'), ('NOTIFY', 'Notification Logs')], max_length=20),
        ),
    ]
