# Generated by Django 5.2.6 on 2025-12-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0012_log_user_alter_log_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nitrogen', models.FloatField()),
                ('phosphorus', models.FloatField()),
                ('potassium', models.FloatField()),
                ('temperature', models.FloatField()),
                ('moisture', models.FloatField()),
                ('ph', models.FloatField()),
                ('conductivity', models.FloatField()),
                ('recommended_crop', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_recommendations', to='detector.workspace')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
