# Generated by Django 5.2.6 on 2025-12-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0013_croprecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='croprecommendation',
            name='all_recommendations',
            field=models.JSONField(default=list),
        ),
    ]
