# Generated by Django 5.2.6 on 2025-12-04 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detector', '0014_croprecommendation_all_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique Serial Number of the ESP32 Device', max_length=100, null=True),
        ),
    ]
